import { ScreenShieldState } from '../types/screenshield';

export const INITIAL_SCREENSHIELD_STATE: ScreenShieldState = {
  userName: 'SRI KARTHIKA',
  privacyScore: 94,
  privacyStreakDays: 7,
  privacyHealth: 'Excellent',
  threatLevel: 'SAFE',
  telemetry: {
    cpuPercent: 18,
    ramPercent: 42,
    memoryGb: 1.2,
    inferenceMs: 82,
    fps: 5,
    aiEngine: 'ONLINE',
    protectionActive: true,
    onDeviceAi: true,
    lastScanSecondsAgo: 2,
  },
  detections: [
    {
      id: 'det-password-1',
      category: 'Password',
      label: 'Password field detected on screen',
      confidence: 96,
      risk: 'CRITICAL',
      timestamp: '09:44:11',
      relativeTime: '2 sec ago',
      box: { x: 6, y: 18, width: 41, height: 22 },
      isProtected: true,
      actionTaken: 'Automatically Protected',
      sourceApp: 'Chrome — Enterprise IAM Login',
    },
    {
      id: 'det-email-3',
      category: 'Email',
      label: 'Executive Inbox & Confidential PII',
      confidence: 91,
      risk: 'MEDIUM',
      timestamp: '09:43:02',
      relativeTime: '14 sec ago',
      box: { x: 6, y: 53, width: 42, height: 34 },
      isProtected: true,
      actionTaken: 'Protected',
      sourceApp: 'Chrome — Mercury Mail',
    },
    {
      id: 'det-otp-2',
      category: 'OTP',
      label: '2FA Verification Code (6-Digit)',
      confidence: 88,
      risk: 'HIGH',
      timestamp: '09:42:35',
      relativeTime: '32 sec ago',
      box: { x: 53, y: 16, width: 40, height: 24 },
      isProtected: true,
      actionTaken: 'Automatically Protected',
      sourceApp: 'Browser — Hardware Token Auth',
    },
    {
      id: 'det-apikey-4',
      category: 'API Key',
      label: 'Production Bearer Secret (sk_live_...)',
      confidence: 95,
      risk: 'CRITICAL',
      timestamp: '09:41:18',
      relativeTime: '1 min ago',
      box: { x: 53, y: 52, width: 40, height: 35 },
      isProtected: true,
      actionTaken: 'Region Blurred',
      sourceApp: 'VS Code — .env.production',
    },
  ],
  activeThreatAlert: {
    id: 'det-password-1',
    category: 'Password',
    label: 'Password field detected on screen.',
    confidence: 96,
    risk: 'CRITICAL',
    timestamp: '09:44:11',
    relativeTime: 'Just now',
    box: { x: 6, y: 18, width: 41, height: 22 },
    isProtected: true,
    actionTaken: 'Automatically Protected',
    sourceApp: 'Chrome — Enterprise IAM Login',
  },
  events: [
    {
      id: 'evt-1',
      timestamp: '09:44:11',
      title: 'Password detected',
      action: 'Region blurred',
      category: 'Password',
      risk: 'CRITICAL',
      confidence: 96,
    },
    {
      id: 'evt-2',
      timestamp: '09:43:02',
      title: 'Email detected',
      action: 'Protected',
      category: 'Email',
      risk: 'MEDIUM',
      confidence: 91,
    },
    {
      id: 'evt-3',
      timestamp: '09:42:35',
      title: 'OTP verification token detected',
      action: 'Automatically Protected',
      category: 'OTP',
      risk: 'HIGH',
      confidence: 88,
    },
    {
      id: 'evt-4',
      timestamp: '09:42:10',
      title: 'Screen scanned',
      action: 'No threats',
      category: 'System',
      risk: 'SAFE',
    },
    {
      id: 'evt-5',
      timestamp: '09:41:18',
      title: 'Production API Key detected',
      action: 'Region blurred',
      category: 'API Key',
      risk: 'CRITICAL',
      confidence: 95,
    },
    {
      id: 'evt-6',
      timestamp: '09:38:50',
      title: 'Financial ledger region shielded',
      action: 'Blackout applied',
      category: 'Banking',
      risk: 'HIGH',
      confidence: 97,
    },
  ],
  zones: [
    {
      id: 'zone-banking',
      name: 'Banking Area',
      policy: 'Always Blackout',
      active: true,
      box: { x: 53, y: 52, width: 40, height: 35 },
      createdAt: '2026-10-01',
    },
    {
      id: 'zone-password',
      name: 'Password Area',
      policy: 'Always Blur',
      active: true,
      box: { x: 6, y: 18, width: 41, height: 22 },
      createdAt: '2026-10-03',
    },
    {
      id: 'zone-auth-modal',
      name: '2FA Token Widget',
      policy: 'Always Monitor',
      active: true,
      box: { x: 53, y: 16, width: 40, height: 24 },
      createdAt: '2026-10-06',
    },
  ],
  protection: {
    mode: 'Blur',
    blurIntensity: 80,
    automaticProtection: true,
    triggerLevel: 'High Risk',
    safeModeActive: false,
    emergencyProtected: false,
    sensitivity: 'HIGH',
  },
  models: [
    {
      id: 'model-ui-det',
      name: 'VISUAL AI',
      version: 'v4.2.1-onnx',
      inferenceTimeMs: 84,
      accuracy: 96.4,
      status: 'ONLINE',
      description: 'Detects password fields, login forms, modals, and sensitive application layouts across active windows.',
      threshold: 85,
    },
    {
      id: 'model-ocr',
      name: 'OCR ENGINE',
      version: 'v3.9.0-int8',
      inferenceTimeMs: 34,
      accuracy: 94.0,
      status: 'ONLINE',
      description: 'On-device optical character recognition scanning active frame buffers for structured tokens, OTPs, and keys.',
      threshold: 80,
    },
    {
      id: 'model-classifier',
      name: 'PRIVACY CLASSIFIER',
      version: 'v5.1.0-distil',
      inferenceTimeMs: 22,
      accuracy: 97.1,
      status: 'ONLINE',
      description: 'Contextual intelligence engine classifying extracted visual regions into real-time privacy risk tiers.',
      threshold: 82,
    },
    {
      id: 'model-face',
      name: 'FACE DETECTION',
      version: 'v2.4.0-lite',
      inferenceTimeMs: 19,
      accuracy: 99.1,
      status: 'OFF',
      description: 'Shoulder-surfing optical guard alerting when secondary viewers look toward your display.',
      threshold: 90,
    },
  ],
  camera: {
    enabled: false,
    viewerDetectionActive: false,
    detectedViewers: 1,
    privacyRisk: 'SAFE',
    autoLockOnShoulderSurf: true,
  },
  settings: {
    monitoringFrequencyFps: 5,
    detectionSensitivity: 'Strict',
    autoStart: true,
    theme: 'dark',
    localProcessingOnly: true,
    dataRetention: 'Minimal',
    eventLogging: true,
    defaultProtectionMethod: 'Blur',
    desktopAlerts: true,
    soundAlerts: false,
  },
  recentApplications: [
    {
      id: 'app-chrome',
      name: 'Chrome',
      windowTitle: 'Enterprise IAM Vault — Sign In',
      status: 'Protected',
      risk: 'SAFE',
      maskedCount: 2,
    },
    {
      id: 'app-vscode',
      name: 'VS Code',
      windowTitle: '.env.production — aegis-core',
      status: 'Shielded',
      risk: 'SAFE',
      maskedCount: 1,
    },
    {
      id: 'app-excel',
      name: 'Excel',
      windowTitle: 'Q4_Executive_Payroll_Ledger.xlsx',
      status: 'Monitored',
      risk: 'LOW',
      maskedCount: 1,
    },
    {
      id: 'app-browser',
      name: 'Browser',
      windowTitle: 'Hardware Token 2FA Portal',
      status: 'Protected',
      risk: 'SAFE',
      maskedCount: 1,
    },
  ],
  smartInsights: [
    {
      id: 'ins-1',
      type: 'insight',
      title: 'AI Insight',
      message: 'Most privacy risks occurred while using browser login pages.',
    },
    {
      id: 'ins-2',
      type: 'recommendation',
      title: 'Security Recommendation',
      message: 'Consider enabling automatic blackout for financial information.',
      actionLabel: 'Enable Blackout Mode',
    },
  ],
  analytics: {
    Today: {
      totalScans: 1284,
      privacyThreats: 12,
      protectedRegions: 27,
      averageRisk: 14,
      riskOverTime: [
        { label: '08:00', risk: 12, scans: 140 },
        { label: '09:00', risk: 29, scans: 210 },
        { label: '10:00', risk: 19, scans: 195 },
        { label: '11:00', risk: 14, scans: 180 },
        { label: '12:00', risk: 9, scans: 110 },
        { label: '13:00', risk: 24, scans: 230 },
        { label: '14:00', risk: 18, scans: 219 },
      ],
      byCategory: [
        { category: 'Passwords & Vaults', count: 15, percentage: 41 },
        { category: '2FA / OTP Codes', count: 10, percentage: 27 },
        { category: 'API & SSH Keys', count: 6, percentage: 16 },
        { category: 'Email & PII', count: 4, percentage: 11 },
        { category: 'Banking / Cards', count: 2, percentage: 5 },
      ],
      protectionActions: [
        { action: 'Automatic Gaussian Blur', count: 31, share: 60 },
        { action: 'Privacy Zone Blackout', count: 12, share: 23 },
        { action: 'Pixelate Redaction', count: 6, share: 11 },
        { action: 'Safe Mode Shield', count: 3, share: 6 },
      ],
      dailyThreatDistribution: [
        { label: '06h', critical: 1, high: 2, medium: 2 },
        { label: '08h', critical: 3, high: 4, medium: 3 },
        { label: '10h', critical: 4, high: 3, medium: 5 },
        { label: '12h', critical: 1, high: 2, medium: 2 },
        { label: '14h', critical: 2, high: 2, medium: 1 },
      ],
    },
    '7 Days': {
      totalScans: 8940,
      privacyThreats: 214,
      protectedRegions: 318,
      averageRisk: 16,
      riskOverTime: [
        { label: 'Mon', risk: 21, scans: 1320 },
        { label: 'Tue', risk: 17, scans: 1410 },
        { label: 'Wed', risk: 24, scans: 1590 },
        { label: 'Thu', risk: 14, scans: 1280 },
        { label: 'Fri', risk: 19, scans: 1490 },
        { label: 'Sat', risk: 8, scans: 920 },
        { label: 'Sun', risk: 11, scans: 930 },
      ],
      byCategory: [
        { category: 'Passwords & Vaults', count: 88, percentage: 41 },
        { category: '2FA / OTP Codes', count: 56, percentage: 26 },
        { category: 'API & SSH Keys', count: 38, percentage: 18 },
        { category: 'Email & PII', count: 21, percentage: 10 },
        { category: 'Banking / Cards', count: 11, percentage: 5 },
      ],
      protectionActions: [
        { action: 'Automatic Gaussian Blur', count: 194, share: 61 },
        { action: 'Privacy Zone Blackout', count: 76, share: 24 },
        { action: 'Pixelate Redaction', count: 32, share: 10 },
        { action: 'Safe Mode Shield', count: 16, share: 5 },
      ],
      dailyThreatDistribution: [
        { label: 'Mon', critical: 8, high: 14, medium: 12 },
        { label: 'Tue', critical: 6, high: 11, medium: 14 },
        { label: 'Wed', critical: 11, high: 16, medium: 15 },
        { label: 'Thu', critical: 5, high: 10, medium: 11 },
        { label: 'Fri', critical: 9, high: 13, medium: 12 },
        { label: 'Sat', critical: 2, high: 5, medium: 6 },
        { label: 'Sun', critical: 3, high: 6, medium: 6 },
      ],
    },
    '30 Days': {
      totalScans: 36420,
      privacyThreats: 842,
      protectedRegions: 1290,
      averageRisk: 15,
      riskOverTime: [
        { label: 'W1', risk: 19, scans: 8400 },
        { label: 'W2', risk: 16, scans: 9120 },
        { label: 'W3', risk: 14, scans: 9650 },
        { label: 'W4', risk: 12, scans: 9250 },
      ],
      byCategory: [
        { category: 'Passwords & Vaults', count: 340, percentage: 40 },
        { category: '2FA / OTP Codes', count: 228, percentage: 27 },
        { category: 'API & SSH Keys', count: 152, percentage: 18 },
        { category: 'Email & PII', count: 78, percentage: 9 },
        { category: 'Banking / Cards', count: 44, percentage: 6 },
      ],
      protectionActions: [
        { action: 'Automatic Gaussian Blur', count: 812, share: 63 },
        { action: 'Privacy Zone Blackout', count: 296, share: 23 },
        { action: 'Pixelate Redaction', count: 116, share: 9 },
        { action: 'Safe Mode Shield', count: 66, share: 5 },
      ],
      dailyThreatDistribution: [
        { label: 'Week 1', critical: 42, high: 88, medium: 95 },
        { label: 'Week 2', critical: 38, high: 79, medium: 84 },
        { label: 'Week 3', critical: 31, high: 72, medium: 91 },
        { label: 'Week 4', critical: 29, high: 68, medium: 85 },
      ],
    },
  },
};
